### ISSUE TITLE
Distributed Testing for Matters IPFS

### ISSUE THREAD

**Issue by tx0c** [thematters/developer-resource#162] opened 2022-10-21 20:58 UTC
to know the real Availability for Matters IPFS:

the test will have:
1. test different age group's articles' IPFS:
   1. for new articles in past 24 hours;
   2. for recent articles, between 24hours up to 1 month;
   3. for old articles (older than 1 month)
   4. from IPNS feed name, a.k.a. including ipns key resolving to IPFS CID;
2. test from different edge locations, (at least have 2 locations in Asia (e.g Taiwan & Hong Kong), 1 NA 1 EU)
3. test with different IPFS gateway (ipfs.io, cloudflare-ipfs.com, pinata?)

the test suites will have a combination of `10 x 3 x 4 x 3 =~ 360` test cases;
and arrange to test at least daily frequency;

then track the IPFS performance for long time:

nice to have some visualization board to show Availability:
1. from an edge location,
2. from an article age group,
3. from a gateway;

References:
1. https://cloud.google.com/blog/products/gcp/available-or-not-that-is-the-question-cre-life-lessons
2. https://sre.google/sre-book/testing-reliability/
3. k6 cloud test https://k6.io/cloud
4. https://www.blazemeter.com/blog/distributed-testing-in-jmeter

**Comment by Carolusian** [comment] 2022-11-02 01:59
## Cohort difference is minimum

As show in the stacked bar chart:

- The cohort difference is quite small
- So when the article is published is relevant, but not a big factor
- The reason leads to ProxyError is currently unknown, either IPFS gateway timeout or due to unstable proxy connection

![image](https://user-images.githubusercontent.com/556963/199375729-2f5de12a-5805-48d8-959d-d7fdfea54afc.png)

## Location has larger impact on the successful rate

- NA and EU has better successful rate than AP
- An unconfirmed inference is AP tend to have longer latency and thus more likely to timeout

![image](https://user-images.githubusercontent.com/556963/199376108-c90b2ddc-44a1-4b02-b53e-e42598ef8f1f.png)

##  Request time used  by cohort 

- Again, no big difference between cohorts

![image](https://user-images.githubusercontent.com/556963/199376453-061954ee-83dd-49dd-bc48-76b04b7504f3.png)

## Request time used by location

- Response to NA locations are the fastest

![image](https://user-images.githubusercontent.com/556963/199376872-2942e282-1ca0-4e21-bc71-61641d71d716.png)
![image](https://user-images.githubusercontent.com/556963/199376894-1b81a108-cfe5-40d8-8245-c89cd4b528f4.png)

**Comment by Carolusian** [comment] 2022-11-02 04:23
## No big difference between gateways in successful rate

![Image](https://user-images.githubusercontent.com/556963/199395099-495c8ad3-e213-4726-b3c1-8ff9f2434fe6.png)

## Successful request time used by gateway

- meson.network is slower as redirection is needed

![Image](https://user-images.githubusercontent.com/556963/199395270-35f99ab1-df47-4d86-99e9-2ca0578db5cb.png)

**Comment by guoliu** [comment] 2022-11-02 07:37
> ## Cohort difference is minimum
> As show in the stacked bar chart:
> 
> * The cohort difference is quite small
> * So when the article is published is relevant, but not a big factor
> * The reason leads to ProxyError is currently unknown, either IPFS gateway timeout or due to unstable proxy connection
> 
> ![image](https://user-images.githubusercontent.com/556963/199375729-2f5de12a-5805-48d8-959d-d7fdfea54afc.png)
> 
> ## Location has larger impact on the successful rate
> * NA and EU has better successful rate than AP
> * An unconfirmed inference is AP tend to have longer latency and thus more likely to timeout
> 
> ![image](https://user-images.githubusercontent.com/556963/199376108-c90b2ddc-44a1-4b02-b53e-e42598ef8f1f.png)
> 
> ## Request time used by cohort
> * Again, no big difference between cohorts
> 
> ![image](https://user-images.githubusercontent.com/556963/199376453-061954ee-83dd-49dd-bc48-76b04b7504f3.png)
> 
> ## Request time used by location
> * Response to NA locations are the fastest
> 
> ![image](https://user-images.githubusercontent.com/556963/199376872-2942e282-1ca0-4e21-bc71-61641d71d716.png) ![image](https://user-images.githubusercontent.com/556963/199376894-1b81a108-cfe5-40d8-8245-c89cd4b528f4.png)

* Could the pattern in geolocation due to most gateway servers are in North America?
* For users using Planet or IPFS in other ways, the latency is in the p2p connection. Do we have a way of measuring latency in p2p connections in different locations?

**Comment by livid** [comment] 2022-11-02 07:42
To measure P2P latency, you can test against an IPFS node running on localhost.

**Comment by Carolusian** [comment] 2022-11-03 03:23
- Yes, it could be due to most gateway servers are in North America, but the quality of the proxies may also be a impacting factor;
- As Livid mentioned, we can probably add test again our own IPFS gateway, either locally or hosted in AWS AP zone.

BTW, The successful rate improves when retrying is added:

![image](https://user-images.githubusercontent.com/556963/199641186-3e7136c5-1226-4e25-953f-5d6f07a3ffac.png)
![image](https://user-images.githubusercontent.com/556963/199641368-7d154268-a18a-4fc4-9853-d605379bfdaa.png)

**Comment by devformatters** [comment] 2022-11-16 09:06
After meeting, there are no more tasks to this issue. Thus, close it.

**Closed by devformatters** 2022-11-16 09:06 UTC
